name: PluginCoordinate
main: ga.saverio.coordinate.Main
version: 1.0
api-version: 1.13
depend: [PlayerHeads]
commands:
   c:
      description: Coordinate di un giocatore
      usage: /<command> <playername>